### ISSUE TITLE
Can't get attribute 'SiLU'

### ISSUE THREAD

**Issue by Stathamy** [BossZard/rotation-yolov5#10]
Traceback (most recent call last):
  File "train.py", line 456, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 69, in train
    ckpt = torch.load(weights, map_location=device)  # load checkpoint
  File "/home/yuanweiqiao/anaconda3/envs/CL/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/yuanweiqiao/anaconda3/envs/CL/lib/python3.7/site-packages/torch/serialization.py", line 842, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'SiLU' on <module 'torch.nn.modules.activation' from '/home/yuanweiqiao/anaconda3/envs/CL/lib/python3.7/site-packages/torch/nn/modules/activation.py'>

**Comment by Stathamy** [comment]
I select wrong weight files.
